class ShowRoomStarter{
	public static void main(String[] args)
	{
		System.out.println("Starting main in ShowRoomStarter");
		ShowRoom showRoom=new ShowRoom();
		System.out.println("ShowRoom name :"+showRoom.name);
		System.out.println("ShowRoom ownerName :"+showRoom.ownerName);
		System.out.println("ShowRoom contactNo :"+showRoom.contactNo);
		System.out.println("ShowRoom openingTime :"+showRoom.openingTime);
		System.out.println("ShowRoom location :"+showRoom.location);
		System.out.println("ShowRoom pincode :"+showRoom.pincode);
		System.out.println("ShowRoom nearLandmark :"+showRoom.nearLandmark);
		System.out.println("ShowRoom type :"+showRoom.type);
		ShowRoom showRoom1=new ShowRoom("Bajaj");
		System.out.println("ShowRoom1 name :"+showRoom1.name);
		System.out.println("ShowRoom1 ownerName :"+showRoom1.ownerName);
		System.out.println("ShowRoom1 contactNo :"+showRoom1.contactNo);
		System.out.println("ShowRoom1 openingTime :"+showRoom.openingTime);
		System.out.println("ShowRoom1 location :"+showRoom.location);
		System.out.println("ShowRoom1 pincode :"+showRoom.pincode);
		System.out.println("ShowRoom1 nearLandmark :"+showRoom.nearLandmark);
		System.out.println("ShowRoom1 type :"+showRoom.type);
		ShowRoom showRoom2=new ShowRoom("Prachi",9876051234l);
		System.out.println("ShowRoom2 name :"+showRoom2.name);
		System.out.println("ShowRoom2 ownerName :"+showRoom2.ownerName);
		System.out.println("ShowRoom2 contactNo :"+showRoom2.contactNo);
		System.out.println("ShowRoom2 openingTime :"+showRoom2.openingTime);
		System.out.println("ShowRoom2 location :"+showRoom2.location);
		System.out.println("ShowRoom2 pincode :"+showRoom2.pincode);
		System.out.println("ShowRoom2 nearLandmark :"+showRoom2.nearLandmark);
		System.out.println("ShowRoom2 type :"+showRoom2.type);
		ShowRoom showRoom3=new ShowRoom(6543217890l);
		System.out.println("ShowRoom3 name :"+showRoom3.name);
		System.out.println("ShowRoom3 ownerName :"+showRoom3.ownerName);
		System.out.println("ShowRoom3 contactNo :"+showRoom3.contactNo);
		System.out.println("ShowRoom3 openingTime :"+showRoom3.openingTime);
		System.out.println("ShowRoom3 location :"+showRoom3.location);
		System.out.println("ShowRoom3 pincode :"+showRoom3.pincode);
		System.out.println("ShowRoom3 nearLandmark :"+showRoom3.nearLandmark);
		System.out.println("ShowRoom3 type :"+showRoom.type);
		ShowRoom showRoom4=new ShowRoom("9am to 10pm","btm");
		System.out.println("ShowRoom4 name :"+showRoom4.name);
		System.out.println("ShowRoom4 ownerName :"+showRoom4.ownerName);
		System.out.println("ShowRoom4 contactNo :"+showRoom4.contactNo);
		System.out.println("ShowRoom4 openingTime :"+showRoom4.openingTime);
		System.out.println("ShowRoom4 location :"+showRoom4.location);
		System.out.println("ShowRoom4 pincode :"+showRoom4.pincode);
		System.out.println("ShowRoom4 nearLandmark :"+showRoom4.nearLandmark);
		System.out.println("ShowRoom4 type :"+showRoom4.type);
		ShowRoom showRoom5=new ShowRoom(577336);
		System.out.println("ShowRoom5 name :"+showRoom5.name);
		System.out.println("ShowRoom5 ownerName :"+showRoom5.ownerName);
		System.out.println("ShowRoom5 contactNo :"+showRoom5.contactNo);
		System.out.println("ShowRoom5 openingTime :"+showRoom5.openingTime);
		System.out.println("ShowRoom5 location :"+showRoom5.location);
		System.out.println("ShowRoom5 pincode :"+showRoom5.pincode);
		System.out.println("ShowRoom5 nearLandmark :"+showRoom5.nearLandmark);
		System.out.println("ShowRoom5 type :"+showRoom.type);
		ShowRoom showRoom6=new ShowRoom(588443,"Petrol bunk");
		System.out.println("ShowRoom6 name :"+showRoom6.name);
		System.out.println("ShowRoom6 ownerName :"+showRoom6.ownerName);
		System.out.println("ShowRoom6 contactNo :"+showRoom6.contactNo);
		System.out.println("ShowRoom6 openingTime :"+showRoom6.openingTime);
		System.out.println("ShowRoom6 location :"+showRoom6.location);
		System.out.println("ShowRoom6 pincode :"+showRoom6.pincode);
		System.out.println("ShowRoom6 nearLandmark :"+showRoom6.nearLandmark);
		System.out.println("ShowRoom6 type :"+showRoom.type);
		ShowRoom showRoom7=new ShowRoom("Maruthi","10am to 9pm","Car");
		System.out.println("ShowRoom7 name :"+showRoom7.name);
		System.out.println("ShowRoom7 ownerName :"+showRoom7.ownerName);
		System.out.println("ShowRoom7 contactNo :"+showRoom7.contactNo);
		System.out.println("ShowRoom7 openingTime :"+showRoom7.openingTime);
		System.out.println("ShowRoom7 location :"+showRoom7.location);
		System.out.println("ShowRoom7 pincode :"+showRoom7.pincode);
		System.out.println("ShowRoom7 nearLandmark :"+showRoom7.nearLandmark);
		System.out.println("ShowRoom7 type :"+showRoom7.type);
		System.out.println("Ending main in ShowRoomStarter");
	}
}